# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: WTF's per line
email: khiekmannblog@fnordbedarf.de
description: > # this means to ignore newlines until "baseurl:"
  Karsten Hiekmann Ã¼ber Software Testing, Test-Automatisierung, Quality 
  Assurance, Agile Testing, TDD und Scrum im weiteren Sinne.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  khiekmann
gulp_username: ProfilNochNichtFreigegeben
linkedin_username: khiekmann
twitter_username: khiekmann
xing_username : Karsten_Hiekmann

# Build settings
markdown: kramdown
#theme: minima
theme: khiekmann-github-io-layout
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
